### PR TITLE
Chain promise optimize

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by aqrln** [comment]
I guess the first patch is already in master? https://github.com/metarhia/MetaSync/commit/a71af4ff3c43e2707f7c2ef4c72509029679a0b6

**Comment by tshemsedinov** [comment]
Rebased with master

**Comment by tshemsedinov** [comment]
I'll open alternative PR with functor-based chaining to compare and land one. This technique is critical for metasync new syntax and new features so we need this decision before other issues.

**Comment by aqrln** [comment]
@tshemsedinov idk, this PR doesn't implement any new functionality, it just refactors code, and the technique to compare other ones with (and the one this PR refers to) is already in master.

**Comment by tshemsedinov** [comment]
Landed in 8b3f4f8

**Pull request closed without merging**
