### PR TITLE
Add code coverage task

### PR DESCRIPTION
**Pull request by DzyubSpirit**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@DzyubSpirit land it please

**Comment by nechaido** [comment]
@dzybspirit @tshemsedinov, I'd suggest.to use something like nyc, because majority of tests aren't based on tap. So code coverage is really better then subject task will output.

**Comment by DzyubSpirit** [comment]
@nechaido, I've read [http://www.node-tap.org/coverage/](here) that tap uses nyc and I've even seen .nyc_output folder. Do you think using nyc directly is better?

**Comment by nechaido** [comment]
@DzyubSpirit yep, because using nyc mom test will show code coverage by both old tests and tap one. Using tap with coverage argument will only show coverage by tap based tests

**Comment by DzyubSpirit** [comment]
@nechaido, oh, now I see, thank you:) . But I don't want to implement nyc task because I don't need it.

**Comment by nechaido** [comment]
@DzyubSpirit I don't need this either.

**Pull request merged**
