### PR TITLE
Fix metasync.find

### PR DESCRIPTION
**Pull request by DzyubSpirit**
Fixes: #82

### CODE REVIEW

**Comment by aqrln** [comment]
@belochub I find it confusing too but I see a reason behind this decision. I feel like it's more of naming issue, though. It would indeed be better to have `Array.prototype`ish `find()` and rename this function to something like `filterOne()`. Despite that, that issue is not related to this PR, the sole purpose of this one is to fix the existing function.

**Comment by aqrln** [comment]
@DzyubSpirit mind @-notifying your fellow reviewers next time you address their review or change-requests comments? I got a freaking great deal of notifications on GitHub and most likely I'll miss your updates unless you ping me. Thanks!

**Comment by belochub** [comment]
@aqrln, if that's the case, then this PR should be changed, because it doesn't just fix the function, it changes function's results to be completely different, even incorrect in my opinion.

**Comment by aqrln** [comment]
@belochub I don't frankly know if that's the case, it's just what I supposed it to do based on my conversation with @nechaido and @DzyubSpirit and Dmytro's approval of this PR, but I may be wrong since I might have missed the point.

**Comment by belochub** [comment]
My proposal is to fix it in a simpler way without changing expected result, check this out: https://github.com/metarhia/MetaSync/commit/d22888ca4a4ac1e9f59103f22a5f3f5fb494f2aa.
@aqrln, @nechaido, @DzyubSpirit, what do you think?

**Comment by aqrln** [comment]
@belochub looks good, but I'd personally prefer to always pass `null` (and not `undefined` as in `done()`) as the first argument when there's no error. That being said, I won't block the PR without it.

**Comment by nechaido** [comment]
@belochub I agree, yet it doesn't correspond to description of `find()`

> done // optional on done callback function(err, result)
>     //   err - error or null
>     //   result - array result

But I think it is probably just a typo we need to fix, same one for `reduce()`.
Also I agree with @aqrln, I'd prefer `null` to be passed if there is no error.

**Comment by belochub** [comment]
@nechaido, yeah, this part in function description looks like a copy-paste typo, we should probably open another PR with fixes to documentation.

**Comment by tshemsedinov** [comment]
But I agree that names are confusing, see #102
@belochub @DzyubSpirit @aqrln

**Comment by tshemsedinov** [comment]
@DzyubSpirit @belochub @nechaido Let's fix PRs, not landing incompatible code

**Comment by DzyubSpirit** [comment]
@tshemsedinov I fixed this PR but still there is question from @belochub at #102 about way for applying fix

**Comment by belochub** [comment]
@DzyubSpirit, even after the fix, it still differs from what I think is a correct way for it to behave.
In case, when no value is found in an array, it must return `undefined`, not empty array.
If you fix this as well, there will be no point in creating new PR.

**Comment by DzyubSpirit** [comment]
@belochub Done

**Comment by belochub** [comment]
@DzyubSpirit, nope, you missed one on line 198.
Also, there is no need to explicitly pass `undefined` to a callback, because passing no argument will as well result in `undefined` value in the callback.

**Comment by DzyubSpirit** [comment]
@belochub Fixed

**Comment by nechaido** [comment]
Landed in c86c5be286dbe78f5780f7ea4f805950eb42087b

**Pull request closed without merging**
