### PR TITLE
Remove unsupported node versions (6.0.0-6.4.0)

### PR DESCRIPTION
**Pull request by lundibundi**
From what I see in the recent PRs you have dropped support from those versions but they are still present in CI and package.json files. This PR removes them.
See: https://github.com/metarhia/metasync/pull/135#issuecomment-304596419.

### CODE REVIEW

**Comment by DzyubSpirit** [comment]
Closes #143

**Comment by DzyubSpirit** [comment]
@tshemsedinov ping

**Comment by DzyubSpirit** [comment]
@tshemsedinov, could you say whether it's satisfying to disable supporting node versions less than 6.5?

**Comment by tshemsedinov** [comment]
Other Metarhia libraries supports 6.0.0-6.4.0 and this is not critical feature @DzyubSpirit

**Comment by DzyubSpirit** [comment]
@tshemsedinov okey, I will create branch for node version bigger than v6.4 and leave it. Also I will change tests with no usage of syntax which breaks them

**Comment by tshemsedinov** [comment]
We landed alternative solution as of now #157

**Pull request closed without merging**
