### PR TITLE
Optimize metasync.map()

### PR DESCRIPTION
**Pull request by NazarPonochevnyi**
The creation of variables was postponed after checking for the availability of data.

### CODE REVIEW

**Comment by DzyubSpirit** [comment]
Do you think creating array with `[]` is faster than with `new Array(0)`?

**Comment by NazarPonochevnyi** [comment]
Thanks, changed.

**Comment by DzyubSpirit** [comment]
@NazarPonochevnyi, sorry that I mislead you: I'm thinking that both options have the same speed. And just asked if you know something that I don't know about that :)

**Comment by NazarPonochevnyi** [comment]
@DzyubSpirit, yes, I ran the tests for a while, and it turned out that both methods pass in the same time. So I reverted commit.

**Comment by NazarPonochevnyi** [comment]
Good)

**Comment by tshemsedinov** [comment]
Landed in df29b3f

**Pull request closed without merging**
