### PR TITLE
Implement metasync some

### LINKED ISSUE #63: Implement metasync.some()
Asynchronous implementation of [Array.prototype.some()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

### PR DESCRIPTION
**Pull request by anxolerd**
Implement metasync.some function, which works similar to
Array.prototype.some but is asynchronous and uses callbacks.

api.metasync.some accepts the following arguments

- items -- the incoming array
- fn(value, cb)  -- check function; value is the value on which check is
  performed and cb is a callback which accepts error or null and
  accepted -- the result of check.
- done -- the some(...) callback which will be executed when some
  finishes. It accepts two arguments: errors or null and result value
  (true/false)

closes #63

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@anxolerd Hello, sorry, I can't review it now, travelling to Beijing, @aqrln can do it I hope, thanks for contribution!

**Comment by anxolerd** [comment]
Fixed typo in commit message.

As for 
> it can start asynchronous functions for all array elements at the same time and return as soon as any of them returns positive result or error.

I afraid it can lead to redundant computations. First element takes bunch of time to complete the check but returns a positive result. All other elements (i.e 1000) take a little less time to complete the computations but all return a negative result. Thus running checks for all "in parallel" will lead to 1000 unnecessary checks.

On the other hand using this approach will speed up the overall result getting when the check of one of the last elements will give the positive result.

**Comment by DzyubSpirit** [comment]
@aqrln Do you have time for reviewing this PR or it can be merged?

**Comment by aqrln** [comment]
@DzyubSpirit LGTM modulo tests, thanks for the ping.

**Comment by DzyubSpirit** [comment]
Landed in d68f8da

**Pull request closed without merging**
